global using Demo.Domain.Features.ExchangeRates;
global using Demo.Domain.Features.Inventory;
global using Demo.Application.Features.ExchangeRates;
global using Demo.Application.Features.Inventory;
global using Demo.Infrastructure.Data;
global using FluentAssertions;
global using Xunit;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Data.Sqlite;
